/*
 * action types
 */

export const actionDef = {
  FETCH_ARTICLES: "FETCH_ARTICLES",
  FETCH_ARTICLES_PENDING: "FETCH_ARTICLES_PENDING",
  FETCH_ARTICLES_SUCCESS: "FETCH_ARTICLES_SUCCESS",
  FETCH_ARTICLES_ERROR: "FETCH_ARTICLES_ERROR",
  UPDATE_SEARCH_STRING: "UPDATE_SEARCH_STRING"
};
