/*
 * action types
 */

export const actionDef = {
  FETCH_ARTICLES: "FETCH_ARTICLES",
  FETCH_ARTICLES_PENDING: "FETCH_ARTICLES_PENDING",
  FETCH_ARTICLES_SUCCESS: "FETCH_ARTICLES_SUCCESS",
  FETCH_ARTICLES_ERROR: "FETCH_ARTICLES_ERROR",
  UPDATE_SEARCH_STRING: "UPDATE_SEARCH_STRING",
  FETCH_HEADLINES_PENDING: "FETCH_HEADLINES_PENDING",
  FETCH_HEADLINES_ERROR: "FETCH_HEADLINES_ERROR",
  FETCH_HEADLINES_SUCCESS: "FETCH_HEADLINES_SUCCESS"
};
